# Generated by Django 4.2 on 2023-05-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_customer_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_in_wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
